### ISSUE TITLE
Application Server

### ISSUE THREAD

**Issue by tanujdhiman** [venugopalkadamba/Multi_Disease_Predictor#8]
![Screenshot (42)](https://user-images.githubusercontent.com/56601466/120840760-417f0680-c588-11eb-96ea-71138082398e.png)

**Comment by venugopalkadamba** [comment]
The application is running fine in the heroku server. Can you just recheck or tell me when you were facing this error. I have tested from my side the application was working fine.

**Comment by tanujdhiman** [comment]
Yes now it is running. After looking at dependencies. I've just created a pull request for changing requirements file please merge it otherwise when other person start installing this model in their system it will throw an error of libraries.

Thanks

**Comment by tanujdhiman** [comment]
Thanks for merging. Actually we can make this project big too. So can we ?

By the way I have sent you a connection request. For further communication.
